#!/usr/bin/env python

import logging
import os
import string
import sys

from os import urandom
from xivo_provd_client import new_provisioning_client

LOCAL_PROVD = "http://localhost:8666/provd"
SCRIPT_NAME = os.path.basename(sys.argv[0])
SCRIPT_EXEC = os.path.join('/', 'var', 'lib', 'xivo-upgrade', SCRIPT_NAME)

logger = logging.getLogger('update_default_phone_passwords')

if os.path.exists(SCRIPT_EXEC):
    sys.exit(0)

logging.basicConfig(level=logging.INFO)


def _generate_phone_password(length):
    chars = string.ascii_letters + string.digits
    return "".join(chars[ord(c) % len(chars)] for c in urandom(length))


logger.debug("Connecting to provd...")
provd_client = new_provisioning_client(LOCAL_PROVD)
config_manager = provd_client.config_manager()

logger.debug("Fetching default device template...")
default_config = config_manager.get('defaultconfigdevice')

logger.info("Updating default phone passwords")
raw_config = default_config['raw_config']

if ('admin_username' not in raw_config and
        'admin_password' not in raw_config and
        'user_username' not in raw_config and
        'user_password' not in raw_config):
    raw_config['admin_username'] = 'admin'
    raw_config['admin_password'] = _generate_phone_password(16)
    raw_config['user_username'] = 'user'
    raw_config['user_password'] = _generate_phone_password(16)
    logger.debug("Updating config...")
    config_manager.update(default_config)
else:
    logger.warn("Phone passwords already set. Not updating.")

# Create empty file as a flag to avoid running the script again
open(SCRIPT_EXEC, 'w').close()

logger.debug('Done.')
