#!/usr/bin/env python3

import logging

from xivo_auth_client import Client as AuthClient
from wazo_plugind_client import Client as PlugindClient
from xivo.config_helper import parse_config_file

_CERT_FILE = '/usr/share/xivo-certs/server.crt'
logger = logging.getLogger('upgrade_admin_ui_official_plugins')
logging.basicConfig(level=logging.INFO)


def _get_auth():
    key_file = parse_config_file('/var/lib/xivo-auth-keys/wazo-plugind-cli-key.yml')
    return {'username': key_file['service_id'],
            'password': key_file['service_key']}


auth_config = _get_auth()
auth_client = AuthClient('localhost',
                         verify_certificate=_CERT_FILE,
                         **auth_config)
token_data = auth_client.token.new('xivo_service', expiration=300)

client = PlugindClient('localhost',
                       verify_certificate=_CERT_FILE,
                       token=token_data['token'])
plugin_list = client.market.list(namespace='official', installed=True)

for plugin in plugin_list['items']:
    for version in plugin['versions']:
        if version['upgradable'] is True:
            logger.info('Upgrading plugin %s', plugin['name'])
            client.plugins.install(None, 'market', {'namespace': 'official', 'name': plugin['name'], 'version': version['version']})
