#!/usr/bin/env python
# -*- coding: utf-8 -*-

# Copyright (C) 2015 Avencall
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>

import os

from kombu import Connection


EXCHANGES = ['xivo', 'xivo-cti', 'xivo-ami', 'xivo-status-updates']
QUEUES = ['xivo-call-logd-queue']


def should_skip():
    return os.environ['XIVO_VERSION_INSTALLED'] >= '15.04'


def main():
    if should_skip():
        return

    with Connection('amqp://guest:guest@localhost:5672//') as conn:
        channel = conn.channel()
        for exchange in EXCHANGES:
            channel.exchange_delete(exchange)
        for queue in QUEUES:
            channel.queue_delete(queue)


if __name__ == '__main__':
    main()
