#!/bin/sh

CERTSCONF=/etc/ca-certificates.conf

if [ "$XIVO_VERSION_INSTALLED" \> '15.20' ]; then
    exit 0
fi

if [ ! -f "$CERTSCONF" ]; then
    exit 0
fi

# if ca-certificates.conf contains at least 1 trusted CA, exit
if [ -n "$(grep -v -e '^!' -e '^#' -e '^$' $CERTSCONF)" ]; then
    exit 0
fi

# enable all certificates
sed -i 's/^!//' "$CERTSCONF"

echo purge | debconf-communicate ca-certificates > /dev/null
dpkg-reconfigure -f noninteractive ca-certificates
