#!/usr/bin/env python
# -*- coding: utf-8 -*-

# Copyright (C) 2015 Avencall
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>

import os
import subprocess
import pika


EXCHANGES = ['xivo', 'xivo-cti', 'xivo-ami', 'xivo-status-updates']


def start_rabbitmq():
    cmd = ['service', 'rabbitmq-server', 'start']
    subprocess.check_call(cmd)


def stop_rabbitmq():
    cmd = ['service', 'rabbitmq-server', 'stop']
    subprocess.check_call(cmd)


def should_skip():
    return os.environ['XIVO_VERSION_INSTALLED'] >= '15.02'


def main():
    if should_skip():
       return

    start_rabbitmq()
    connection = pika.BlockingConnection()
    channel = connection.channel()
    for exchange in EXCHANGES:
       try:
          channel.exchange_delete(exchange=exchange)
       except Exception:
          channel = connection.channel()
    stop_rabbitmq()


if __name__ == '__main__':
    main()
